version: '3.9'

services:
  mongodb:
    image: mongo:6
    container_name: carstore-mongo
    ports:
      - "27017:27017"
    networks:
      - carstore-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  vendas-app:
    build: .
    image: fabriciofsousa/fiap-carstore-vendas:latest
    container_name: fiap-carstore-vendas
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/carstore
      veiculo.api.url: http://veiculos-app:8080
      cliente.api.url: http://clientes-app:8080
    ports:
      - "8083:8080"
    networks:
      - carstore-network
    healthcheck:
      test: [ "CMD-SHELL", "\
        curl -f http://clientes-app:8080/actuator/health && \
        curl -f http://veiculos-app:8080/actuator/health && \
        curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  carstore-network:
    external: true
