spring.application.name=vendas
veiculo.api.url=http://localhost:8081
cliente.api.url=http://localhost:8082

#veiculo.api.url=http://veiculo:8081
#spring.data.mongodb.uri=mongodb://mongodb:27017/carstore

spring.data.mongodb.uri=mongodb://localhost:27017/carstore
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=carstore
spring.data.mongodb.username=
spring.data.mongodb.password=