spring:
  application:
    name: vendas
  data:
    mongodb:
      uri: mongodb://localhost:27017/vendas_db
  devtools:
    restart:
      enabled: false

  logging:
      level:
        org.springframework.security: DEBUG


veiculo:
  api:
    url: ${VEICULO_API_URL}

cliente:
  api:
    url: ${CLIENTE_API_URL}

