spring:
  application:
    name: vendas
  data:
    mongodb:
      uri: ${DB_URI}
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      username: ""
      password: ""
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/cognito"
            client-name: Cognito
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/${COGNITO_USER_POOL_ID}
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/${COGNITO_USER_POOL_ID}
    app:
      security:
        cognito:
          groups-claim: cognito:groups

    logging:
      level:
        org.springframework.security: DEBUG
cognito:
   user-pool-id: ${COGNITO_USER_POOL_ID}
   client-id: ${COGNITO_CLIENT_ID}
   region: ${COGNITO_REGION}

veiculo:
  api:
    url: ${VEICULO_API_URL}

cliente:
  api:
    url: ${CLIENTE_API_URL}

